### ISSUE TITLE
The performActivity commands have issues when we test with more participants.

### ISSUE THREAD

**Issue by vigneshcbv** [aws-samples/amazon-chime-sdk-meetings-load-test#9]
We attempted to do a performance test with 75 EC2 instances, each running 10 browsers; All 750 clients were properly created, but after we dropped the activity file to join the session, certain threads failed to run the activity commands; In our case, out of 750, roughly 690 entered the session, and more than 50 threads were not logged into session at all; Have you seen this type of behavior? what is the maximum number of participants tested in a single/multiple meeting using this framework?;

**Comment by RidipDe** [comment]
A lot depends on the EC2 instance type that you are using to deploy the threads.

In order to simulate the ideal scenario of every attendee joining and turning on the video, it is recommend to run at most two meeting attendee sessions per EC2 instance of C5 xl as the CPU, in addition to spawning threads to open browsers and starting the meetings, it also engages in running the WebRTC threads which utilizes a good chunk of the available CPU resources.

As the load per given EC2 instance increases, meeting join failures might occur based on the intensity of the activities being performed per meeting.
 
The cost for running C5 instances per hour can be found [here](https://aws.amazon.com/ec2/pricing/on-demand/).
